services:
  database:
    image: postgres:16
    container_name: currency_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - currency_database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: currency_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://admin:admin@database:5432/currency_db
      NBP_API_URL: https://api.nbp.pl/api/exchangerates/tables/a
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: currency_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  currency_database_data:
